export const ENGINEERING_AGENT_PHASES = {
  INITIALIZED: 'INITIALIZED',
  PLANNING: 'PLANNING',
  CODE_GENERATION: 'CODE_GENERATION',
  BUILD_AND_TEST: 'BUILD_AND_TEST',
  VERIFICATION: 'VERIFICATION',
  DEPLOYMENT: 'DEPLOYMENT',
  MONITORING: 'MONITORING',
  RCA: 'RCA',
  SELF_HEALING: 'SELF_HEALING',
  CODE_REVIEW: 'CODE_REVIEW',
  COST_ANALYSIS: 'COST_ANALYSIS',
  TASK_DECOMPOSITION: 'TASK_DECOMPOSITION',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const;

export type EngineeringAgentPhase = typeof ENGINEERING_AGENT_PHASES[keyof typeof ENGINEERING_AGENT_PHASES];
